basePath: /api/v1
definitions:
  model.Transactions:
    properties:
      amount:
        type: integer
      createAt:
        type: string
      description:
        type: string
      destination:
        type: string
      id:
        type: string
      paymentMethodID:
        type: string
      sourceWalletID:
        type: string
      userId:
        type: string
    type: object
  model.Users:
    properties:
      createdAt:
        type: string
      disableAt:
        type: string
      email:
        type: string
      fullName:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      password:
        type: string
      passwordConfirm:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
      userName:
        type: string
    type: object
  model.Wallet:
    properties:
      balance:
        type: integer
      createdAt:
        type: string
      id:
        type: string
      rekeningUser:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
    type: object
  req.AuthLoginRequest:
    properties:
      loginOption:
        $ref: '#/definitions/req.loginOption'
      password:
        type: string
    required:
    - password
    type: object
  req.AuthRegisterRequest:
    properties:
      email:
        type: string
      fullName:
        maxLength: 50
        minLength: 3
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
      phoneNumber:
        maxLength: 15
        minLength: 10
        type: string
      userName:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - fullName
    - password
    - passwordConfirm
    - phoneNumber
    - userName
    type: object
  req.TopUpRequest:
    properties:
      amount:
        minimum: 10000
        type: integer
      paymentMethodId:
        type: string
      userId:
        type: string
      walletID:
        type: string
    required:
    - amount
    - paymentMethodId
    - userId
    - walletID
    type: object
  req.TransferRequest:
    properties:
      amount:
        type: integer
      description:
        type: string
      destination_wallet_id:
        type: string
      payment_method_id:
        type: string
      source_user_id:
        type: string
      source_wallet_id:
        type: string
    type: object
  req.UpdateAccountRequest:
    properties:
      email:
        type: string
      fullName:
        maxLength: 50
        minLength: 3
        type: string
      id:
        type: string
      phoneNumber:
        maxLength: 15
        minLength: 10
        type: string
      username:
        maxLength: 30
        minLength: 3
        type: string
    required:
    - email
    - fullName
    - id
    - phoneNumber
    - username
    type: object
  req.UpdatePasswordRequest:
    properties:
      currentPassword:
        type: string
      newPassword:
        type: string
      newPasswordConfirm:
        type: string
      userName:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - currentPassword
    - newPassword
    - newPasswordConfirm
    - userName
    type: object
  req.loginOption:
    properties:
      email:
        type: string
      phoneNumber:
        type: string
      userName:
        type: string
    type: object
  resp.DisableAccountResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  resp.GetTransactionsResponse:
    properties:
      amount:
        type: integer
      description:
        type: string
      destination_wallet_id:
        type: string
      id_transaction:
        type: string
      payment_method:
        $ref: '#/definitions/resp.paymentMethod'
      time_of_transaction:
        type: string
      user:
        $ref: '#/definitions/resp.user'
      wallet:
        $ref: '#/definitions/resp.wallet'
    type: object
  resp.LoginResponse:
    properties:
      message:
        type: string
      status:
        type: integer
      token:
        type: string
      user_name:
        type: string
    type: object
  resp.RegisterResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  resp.UpdateAccountRespone:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  resp.UpdatePasswordResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  resp.paymentMethod:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  resp.user:
    properties:
      user_name:
        type: string
    type: object
  resp.wallet:
    properties:
      balance:
        type: integer
      rekening_user:
        type: string
    type: object
info:
  contact: {}
  title: dompet-online
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Auth login
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.LoginResponse'
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Auth register
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.AuthRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/resp.RegisterResponse'
      tags:
      - Auth
  /transactions/{userId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Get History Transaction
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.GetTransactionsResponse'
      security:
      - Bearer: []
      tags:
      - Transaction
  /transactions/topUp:
    put:
      consumes:
      - application/json
      parameters:
      - description: TopUp
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.TopUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transactions'
      security:
      - Bearer: []
      tags:
      - Transaction
  /transactions/transfer:
    put:
      consumes:
      - application/json
      parameters:
      - description: Transfer
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.TransferRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Transactions'
      security:
      - Bearer: []
      tags:
      - Transaction
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Users'
      security:
      - Bearer: []
      tags:
      - Admin
    patch:
      consumes:
      - application/json
      parameters:
      - description: Change Password
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.UpdatePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.UpdatePasswordResponse'
      security:
      - Bearer: []
      tags:
      - User
    put:
      consumes:
      - application/json
      parameters:
      - description: Update Personal Information
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/req.UpdateAccountRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.UpdateAccountRespone'
      security:
      - Bearer: []
      tags:
      - User
  /users/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Disable Account
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.DisableAccountResponse'
      security:
      - Bearer: []
      tags:
      - User
  /users/{phoneNumber}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User PhoneNumber
        in: path
        name: phoneNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Users'
      security:
      - Bearer: []
      tags:
      - Admin
  /wallets/{userId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Get Wallet
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Wallet'
      security:
      - Bearer: []
      tags:
      - Wallet
schemes:
- http
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
